Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 5432, host: 5433
  config.vm.hostname = "Postgres-python-pip-psycopg2"

  config.vm.provider "virtualbox" do |vb|
  vb.gui = false
  vb.memory = "4048"
  vb.name = config.vm.hostname
  end

  config.vm.provision "shell", inline: <<-SHELL
	
	sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
	wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
	sudo apt-get update
	sudo apt-get -y install postgresql 
	sudo apt-get -y install libpq-dev
	sudo apt-get -y install python3 python3-pip
	sudo pip3 install psycopg2 Django

  SHELL
  
  config.vm.provision "file", source: "emptyfile.txt", destination: "emptyfile.txt"

end
